# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGQ5YmU0NjgxNTg1YjI5YmExMjgzYmViZTU0NjZkMjdhODM5OTQ5ZjRhOTE1MTIzNGRhOTczYjhhZTM3OTg2MGM3OTBjY2ZhYTI3MWNiYzczNzI5ZjZkMzU5ZDdkNzgxOTRkY2Y5YjliNDRjNWI2NmZjNTdjODc0NWEwNjdiMDk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
